// Renders the server icon into src/icon.ts. Run with `pnpm make:icon`.
//
// MCP clients MUST support PNG and only SHOULD support SVG, so we ship both.
// Both are embedded as data: URIs rather than fetched from this Worker — the
// spec tells clients to verify icons are same-origin, and the MCP server info
// is built before we know the request's origin.

import { writeFile } from "node:fs/promises";
import { deflateSync } from "node:zlib";

const SIZE = 48;
const GREEN = [29, 185, 84] as const; // #1db954, the accent used everywhere else
const BARS = [
	{ x: 8, h: 16 },
	{ x: 17, h: 28 },
	{ x: 26, h: 22 },
	{ x: 35, h: 34 },
];
const BAR_W = 5;

type Rect = { x: number; y: number; w: number; h: number; r: number };

const plate: Rect = { x: 0, y: 0, w: SIZE, h: SIZE, r: 10 };
const bars: Rect[] = BARS.map(({ x, h }) => ({
	x,
	y: (SIZE - h) / 2,
	w: BAR_W,
	h,
	r: BAR_W / 2,
}));

/** Coverage of a point by a rounded rect, 0 or 1. */
function inside(px: number, py: number, r: Rect): boolean {
	const dx = Math.max(r.x + r.r - px, 0, px - (r.x + r.w - r.r));
	const dy = Math.max(r.y + r.r - py, 0, py - (r.y + r.h - r.r));
	if (px < r.x || px > r.x + r.w || py < r.y || py > r.y + r.h) return false;
	return dx * dx + dy * dy <= r.r * r.r;
}

const SS = 4; // supersampling factor, for antialiased edges

function pixel(px: number, py: number): [number, number, number, number] {
	let plateHits = 0;
	let barHits = 0;
	for (let sy = 0; sy < SS; sy++) {
		for (let sx = 0; sx < SS; sx++) {
			const x = px + (sx + 0.5) / SS;
			const y = py + (sy + 0.5) / SS;
			if (!inside(x, y, plate)) continue;
			plateHits += 1;
			if (bars.some((b) => inside(x, y, b))) barHits += 1;
		}
	}
	const samples = SS * SS;
	if (plateHits === 0) return [0, 0, 0, 0];
	const white = barHits / plateHits;
	const mix = (c: number) => Math.round(c + (255 - c) * white);
	return [mix(GREEN[0]), mix(GREEN[1]), mix(GREEN[2]), Math.round((plateHits / samples) * 255)];
}

const CRC_TABLE = Array.from({ length: 256 }, (_, n) => {
	let c = n;
	for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
	return c >>> 0;
});

function crc32(buf: Uint8Array): number {
	let c = 0xffffffff;
	for (const byte of buf) c = CRC_TABLE[(c ^ byte) & 0xff]! ^ (c >>> 8);
	return (c ^ 0xffffffff) >>> 0;
}

function chunk(type: string, data: Uint8Array): Buffer {
	const head = Buffer.alloc(8);
	head.writeUInt32BE(data.length, 0);
	head.write(type, 4, "ascii");
	const body = Buffer.concat([head.subarray(4), data]);
	const tail = Buffer.alloc(4);
	tail.writeUInt32BE(crc32(body), 0);
	return Buffer.concat([head, data, tail]);
}

function renderPng(): Buffer {
	const raw = Buffer.alloc(SIZE * (SIZE * 4 + 1));
	let i = 0;
	for (let y = 0; y < SIZE; y++) {
		raw[i++] = 0; // filter: none
		for (let x = 0; x < SIZE; x++) {
			const [r, g, b, a] = pixel(x, y);
			raw[i++] = r;
			raw[i++] = g;
			raw[i++] = b;
			raw[i++] = a;
		}
	}
	const ihdr = Buffer.alloc(13);
	ihdr.writeUInt32BE(SIZE, 0);
	ihdr.writeUInt32BE(SIZE, 4);
	ihdr[8] = 8; // bit depth
	ihdr[9] = 6; // colour type: RGBA
	return Buffer.concat([
		Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
		chunk("IHDR", ihdr),
		chunk("IDAT", deflateSync(raw, { level: 9 })),
		chunk("IEND", Buffer.alloc(0)),
	]);
}

function renderSvg(): string {
	const rect = (r: Rect, fill: string) =>
		`<rect x="${r.x}" y="${r.y}" width="${r.w}" height="${r.h}" rx="${r.r}" fill="${fill}"/>`;
	return [
		`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${SIZE} ${SIZE}" width="${SIZE}" height="${SIZE}">`,
		rect(plate, "#1db954"),
		...bars.map((b) => rect(b, "#fff")),
		"</svg>",
	].join("");
}

const png = renderPng();
const svg = renderSvg();

await writeFile(
	new URL("../src/icon.ts", import.meta.url),
	`// Generated by scripts/make-icon.ts — edit the shapes there, not here.
// An equalizer mark rather than Spotify's own logo, which is trademarked.

export const ICON_SVG =
\t"${svg.replaceAll('"', '\\"')}";

export const ICON_PNG_BASE64 =
\t"${png.toString("base64")}";
`,
);

console.log(`icon: ${png.length} B png, ${svg.length} B svg -> src/icon.ts`);
