// Generated by scripts/make-icon.ts — edit the shapes there, not here.
// An equalizer mark rather than Spotify's own logo, which is trademarked.

export const ICON_SVG =
	'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48" width="48" height="48"><rect x="0" y="0" width="48" height="48" rx="10" fill="#1db954"/><rect x="8" y="16" width="5" height="16" rx="2.5" fill="#fff"/><rect x="17" y="10" width="5" height="28" rx="2.5" fill="#fff"/><rect x="26" y="13" width="5" height="22" rx="2.5" fill="#fff"/><rect x="35" y="7" width="5" height="34" rx="2.5" fill="#fff"/></svg>';

export const ICON_PNG_BASE64 =
	"iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAYAAABXAvmHAAAA80lEQVR42u2awQkDIRBFbcR6cvVgARaRfraEPdtA0kDudpAWDIILS9hEs0icP/yBYRGU/Y8ZRGc05oPZ6IONfrXRJxt9nuSpagim12z0brLobzCuJX4RKPzdF2TxxxA1bTKYuz1AAgRI+90mg3owdZsSIehyu+b785GLlW8ZN9asotJnE79ZGTfTSFJKHFlrjZkUelkAJ0IvC+DMj+EAetJMNEBPmokGGDXnZ4BRoZ8GMCr00wD+KY4ABCAAAQhAAAIQgIc5HqeVXWh4pdRyqWdhi6VFwcVd+PI6fIMDu8UE3+RT0WaFb3SreGqg4rEH4nObF+aSN1Puo4+dAAAAAElFTkSuQmCC";
